# Generated by Django 5.1.3 on 2024-11-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lux_clothing", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="variant",
        ),
        migrations.AddField(
            model_name="product",
            name="variant",
            field=models.ManyToManyField(
                related_name="product", to="lux_clothing.productvariant"
            ),
        ),
    ]
