# Generated by Django 5.1.3 on 2024-11-30 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lux_clothing", "0003_remove_product_variant_product_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="variant",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_variant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_item",
                to="lux_clothing.productvariant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="variant",
            field=models.ManyToManyField(
                related_name="product_variant", to="lux_clothing.product"
            ),
        ),
    ]
