# Generated by Django 5.1.3 on 2024-11-30 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lux_clothing", "0005_rename_variant_productvariant_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="product",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_variant",
                to="lux_clothing.product",
            ),
            preserve_default=False,
        ),
    ]
