# Generated by Django 5.1.3 on 2024-12-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lux_clothing", "0006_remove_productvariant_product_productvariant_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_items",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Cart", "Cart"),
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Expired", "Expired"),
                    ("Canceled", "Canceled"),
                    ("Processing", "Processing"),
                    ("Completed", "Completed"),
                ],
                default="Cart",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_items",
            field=models.ManyToManyField(
                related_name="order", to="lux_clothing.orderitem"
            ),
        ),
    ]
