# Generated by Django 5.1.3 on 2024-12-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lux_clothing", "0010_remove_orderitem_product_variant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.ManyToManyField(
                related_name="profile", to="lux_clothing.address"
            ),
        ),
    ]
