# Generated by Django 5.1.3 on 2024-12-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lux_clothing", "0011_remove_profile_address_profile_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="address",
            new_name="addresses",
        ),
    ]
