# Generated by Django 5.1.3 on 2024-12-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lux_clothing", "0014_remove_order_profile_remove_orderitem_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
