# Generated by Django 5.1.3 on 2025-01-01 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lux_clothing", "0017_alter_address_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="default_address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="addresses",
        ),
        migrations.AddField(
            model_name="profile",
            name="addresses",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="lux_clothing.address",
            ),
            preserve_default=False,
        ),
    ]
