# Generated by Django 5.1.3 on 2025-01-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lux_clothing", "0018_remove_profile_default_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="addresses",
        ),
        migrations.AddField(
            model_name="profile",
            name="addresses",
            field=models.ManyToManyField(
                related_name="profile", to="lux_clothing.address"
            ),
        ),
    ]
