# Generated by Django 5.1.3 on 2025-01-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lux_clothing", "0020_address_inactive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Expired", "Expired"),
                    ("Canceled", "Canceled"),
                    ("Processing", "Processing"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=15,
            ),
        ),
    ]
