# Generated by Django 5.1.3 on 2025-01-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lux_clothing", "0021_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="favorite_products",
            field=models.ManyToManyField(
                related_name="profile", to="lux_clothing.product"
            ),
        ),
    ]
