# Generated by Django 5.1.3 on 2025-01-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lux_clothing", "0022_profile_favorite_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="favorite_products",
            field=models.ManyToManyField(
                blank=True, related_name="profile", to="lux_clothing.product"
            ),
        ),
    ]
