# Generated by Django 5.1.3 on 2025-01-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lux_clothing", "0023_alter_profile_favorite_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
