# Generated by Django 5.1.3 on 2025-01-15 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lux_clothing", "0026_forwhom_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="producthead",
            name="for_whom",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_head",
                to="lux_clothing.forwhom",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producthead",
            name="style",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_head",
                to="lux_clothing.style",
            ),
            preserve_default=False,
        ),
    ]
