# Generated by Django 5.1.3 on 2025-01-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="primary_email",
            field=models.BooleanField(default=True),
        ),
    ]
