# Generated by Django 5.1.3 on 2025-01-24 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_emailconfirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfirmation",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="emailconfirmation",
            name="key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
